get http://localhost:7008/api/ping

###

get http://localhost:7008/api/diagnoses

###

get http://localhost:7008/api/patients

###
get http://localhost:7008/api/patients/d2fc1960-bd00-11ed-8f94-05ce3b845442

###
post http://localhost:7008/api/patients
content-type: application/json

{
    "name": "Matti Luukkainen",
    "dateOfBirth": "1971-04-09",
    "ssn": "090471-8890",
    "gender": "male",
    "occupation": "Digital evangelist"
}

